import { GitHubAPIClient } from './apiClient.js';

/**
 * Handles repository operations for p5.nvim
 */
export class RepoOperations {
  constructor(githubToken, targetRepo = 'prjctimg/p5.nvim') {
    this.github = new GitHubAPIClient(githubToken);
    this.targetRepo = targetRepo;
    this.branchName = 'main';
  }

  /**
   * Commit generated documentation files to p5.nvim repository
   * @param {Map} generatedFiles - Map of generated files
   * @param {string} commitMessage - Commit message
   * @returns {Promise<Object>} Operation result
   */
  async commitDocumentation(generatedFiles, commitMessage) {
    console.log('📝 Committing documentation to p5.nvim repository...');
    
    try {
      const [owner, repo] = this.targetRepo.split('/');
      
      // Check if repository exists
      const exists = await this.github.repositoryExists(owner, repo);
      if (!exists) {
        return {
          success: false,
          error: `Target repository ${this.targetRepo} does not exist`
        };
      }
      
      // Create a feature branch for the changes
      const branchName = `update-docs-${Date.now()}`;
      const branchResult = await this.github.createBranch(owner, repo, branchName);
      
      if (!branchResult.success) {
        return {
          success: false,
          error: `Failed to create branch: ${branchResult.error}`
        };
      }
      
      console.log(`🌿 Created branch: ${branchName}`);
      
      // Commit each file
      const commitResults = [];
      for (const [moduleName, filepath] of generatedFiles) {
        const content = await import('fs/promises').then(fs => fs.readFile(filepath, 'utf8'));
        const filename = filepath.split('/').pop();
        
        const fileResult = await this.github.createOrUpdateFile(
          owner, 
          repo, 
          `doc/${filename}`, 
          content, 
          `${commitMessage}: Update ${filename}`,
          branchName
        );
        
        commitResults.push({
          module: moduleName,
          file: filename,
          result: fileResult
        });
        
        if (fileResult.success) {
          console.log(`✅ Committed ${filename}`);
        } else {
          console.warn(`⚠️  Failed to commit ${filename}: ${fileResult.error}`);
        }
      }
      
      // Generate tags file
      const tagsContent = this.generateTagsContent();
      const tagsResult = await this.github.createOrUpdateFile(
        owner,
        repo,
        'doc/tags',
        tagsContent,
        `${commitMessage}: Update tags`,
        branchName
      );
      
      if (tagsResult.success) {
        console.log('✅ Committed tags file');
      }
      
      // Create pull request
      const prResult = await this.createPullRequest(
        owner,
        repo,
        branchName,
        commitMessage
      );
      
      if (prResult.success) {
        console.log(`🎉 Created pull request: ${prResult.pullRequest.html_url}`);
      }
      
      return {
        success: true,
        commits: commitResults,
        tags: tagsResult,
        pullRequest: prResult.pullRequest,
        branch: branchName
      };
      
    } catch (error) {
      console.error('❌ Error committing documentation:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Create pull request for documentation updates
   * @param {string} owner - Repository owner
   * @param {string} repo - Repository name
   * @param {string} branchName - Feature branch name
   * @param {string} commitMessage - Commit message
   * @returns {Promise<Object>} PR result
   */
  async createPullRequest(owner, repo, branchName, commitMessage) {
    const title = this.extractTitleFromMessage(commitMessage);
    const body = this.generatePRBody(commitMessage);
    
    return await this.github.createPullRequest(
      owner,
      repo,
      title,
      body,
      `${owner}:${branchName}`,
      this.branchName
    );
  }

  /**
   * Extract title from commit message
   * @param {string} message - Commit message
   * @returns {string} Title
   */
  extractTitleFromMessage(message) {
    const lines = message.split('\n');
    return lines[0].substring(0, 70); // Limit to 70 characters
  }

  /**
   * Generate pull request body
   * @param {string} commitMessage - Commit message
   * @returns {string} PR body
   */
  generatePRBody(commitMessage) {
    const timestamp = new Date().toISOString();
    
    return `Automated documentation update from p5.js

${commitMessage}

Generated by: p5.js Documentation Automation
Timestamp: ${timestamp}
Source: https://github.com/prjctimg/automata

This PR updates the Neovim help pages for p5.js based on the latest
JSDoc comments from the p5.js source code.

## Changes
- Updated all module documentation files
- Generated new tags file
- Added new symbols and updated existing ones

## Verification
Please review the changes and ensure:
- All new symbols are properly documented
- No duplicate tags are generated
- Documentation formatting is correct
- Links between symbols work properly`;
  }

  /**
   * Get current documentation files in repository
   * @returns {Promise<Array>} Array of file paths
   */
  async getCurrentDocumentation() {
    try {
      const [owner, repo] = this.targetRepo.split('/');
      const files = [];
      
      // List contents of doc directory
      const docDirResult = await this.github.getFileContent(owner, repo, 'doc');
      
      if (docDirResult.success && docDirResult.type === 'dir') {
        // Would need to use directory listing API, but for now we'll try common files
        const commonFiles = [
          'p5-shape.txt', 'p5-color.txt', 'p5-typography.txt',
          'p5-image.txt', 'p5-transform.txt', 'p5-environment.txt',
          'p5-3d.txt', 'p5-rendering.txt', 'p5-math.txt',
          'p5-io.txt', 'p5-events.txt', 'p5-data.txt',
          'p5-structure.txt', 'p5-dom.txt', 'p5-constants.txt',
          'tags'
        ];
        
        for (const file of commonFiles) {
          const fileResult = await this.github.getFileContent(owner, repo, `doc/${file}`);
          if (fileResult.success) {
            files.push(file);
          }
        }
      }
      
      return {
        success: true,
        files
      };
      
    } catch (error) {
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Generate tags file content
   * @returns {string} Tags file content
   */
  generateTagsContent() {
    // This would be generated from the actual tag manager
    // For now, return a placeholder
    return `!_TAG_FILE_SORTED\t1\t/unknown field/
!_TAG_FILE_ENCODING\tutf-8\t/unknown field/
!_TAG_FILE_FORMAT\t2\t/extended format; --format=1 will not compatible with vi/
!_TAG_PROGRAM_AUTHOR\tprjctimg
!_TAG_PROGRAM_NAME\tp5.js Documentation Automation
!_TAG_PROGRAM_URL\thttps://github.com/prjctimg/automata

# Tags will be generated when documentation is created
`;
  }

  /**
   * Clean up old branches (maintenance)
   * @param {number} olderThanDays - Age threshold in days
   * @returns {Promise<Object>} Cleanup result
   */
  async cleanupOldBranches(olderThanDays = 7) {
    try {
      const [owner, repo] = this.targetRepo.split('/');
      const cutoffDate = new Date();
      cutoffDate.setDate(cutoffDate.getDate() - olderThanDays);
      
      // List all branches
      const { data: branches } = await this.octokit.rest.repos.listBranches({
        owner,
        repo,
        per_page: 100
      });
      
      const docBranches = branches.filter(branch => 
        branch.name.startsWith('update-docs-') || 
        branch.name.startsWith('docs-')
      );
      
      const deletedBranches = [];
      
      for (const branch of docBranches) {
        const { data: branchData } = await this.octokit.rest.repos.getBranch({
          owner,
          repo,
          branch: branch.name
        });
        
        if (new Date(branchData.commit.commit.author.date) < cutoffDate) {
          try {
            await this.octokit.rest.git.deleteRef({
              owner,
              repo,
              ref: `heads/${branch.name}`
            });
            
            deletedBranches.push(branch.name);
            console.log(`🗑️  Deleted old branch: ${branch.name}`);
          } catch (error) {
            console.warn(`⚠️  Failed to delete branch ${branch.name}:`, error.message);
          }
        }
      }
      
      return {
        success: true,
        deletedBranches,
        totalBranches: docBranches.length
      };
      
    } catch (error) {
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Get repository statistics
   * @returns {Promise<Object>} Repository stats
   */
  async getRepositoryStats() {
    try {
      const [owner, repo] = this.targetRepo.split('/');
      
      const [repoData, commitsData] = await Promise.all([
        this.github.getRepository(owner, repo),
        this.octokit.rest.repos.listCommits({
          owner,
          repo,
          per_page: 1
        })
      ]);
      
      if (repoData.success) {
        return {
          success: true,
          stats: {
            name: repoData.repository.full_name,
            description: repoData.repository.description,
            stars: repoData.repository.stargazers_count,
            forks: repoData.repository.forks_count,
            language: repoData.repository.language,
            lastCommit: commitsData.data[0]?.sha,
            lastCommitDate: commitsData.data[0]?.commit?.author?.date
          }
        };
      }
      
      return repoData;
      
    } catch (error) {
      return {
        success: false,
        error: error.message
      };
    }
  }
}