#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

console.log('🚀 Starting p5 documentation bundling... 📚✨');

const outputDir = 'doc';
const assetsDir = 'assets';
const typesFile = path.join(assetsDir, 'types', 'p5.d.ts');

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Helper function to run pandoc
function runPandoc(inputFile, outputFile, title) {
  try {
    const cmd = `pandoc "${inputFile}" -f markdown -t vimdoc --metadata="title:${title}" -o "${outputFile}"`;
    execSync(cmd, { stdio: 'pipe' });
    return true;
  } catch (error) {
    console.warn(`⚠️  Pandoc failed for ${inputFile}: ${error.message}`);
    return false;
  }
}

// Helper function to create Vimdoc format with emojis
function createVimdocContent(moduleName, functions, p5Version, timestamp) {
  const moduleEmojis = {
    'accessibility': '♿',
    'color': '🎨',
    'core': '⚙️',
    'data': '📊',
    'dom': '🌐',
    'events': '🖱️',
    'image': '🖼️',
    'io': '📁',
    'math': '🔢',
    'typography': '📝',
    'utilities': '🛠️',
    'webgl': '🎮'
  };

  const emoji = moduleEmojis[moduleName] || '📚';
  
  // Create table of contents
  const tocFunctions = functions.map(func => 
    `  - ${func.name}()             |p5-${moduleName}-${func.name}|`
  ).join('\n  ');

  // Create function documentation
  const functionDocs = functions.map(func => {
    const params = func.params.map(p => 
      `  - **${p.name}**: ${p.description}`
    ).join('\n  ');

    return `
\`${func.name}()\`                                          |p5-${moduleName}-${func.name}|

*   ${func.description}
${params}

  - **Returns**: ${func.returns}

📂 *Sub-module: ${func.subModule || 'unknown'}*

---`;
  }).join('\n');

  return `*p5-${moduleName}*                             p5.js ${moduleName} docs

==============================================================================
Table of Contents                      *p5-${moduleName}-table-of-contents*

1. Functions                                           |p5-${moduleName}-functions|
${tocFunctions}

${emoji} ${moduleName} module for p5.js

📦 p5.js Version: ${p5Version}~
⏰ Last Updated: ${timestamp}~

==============================================================================
2. Functions                                           |p5-${moduleName}-functions|

${functionDocs}

==============================================================================
Generated by p5.nvim documentation generator <https://github.com/prjctimg/p5.nvim>

vim:tw=78:ts=8:ft=help:norl:
`;
}

function extractDocumentation() {
  console.log('📖 Reading TypeScript definitions...');
  
  if (!fs.existsSync(typesFile)) {
    console.error('❌ TypeScript definitions file not found:', typesFile);
    process.exit(1);
  }
  
  const content = fs.readFileSync(typesFile, 'utf8');
  
  // Get p5 version and timestamp
  const p5Version = '1.7.7'; // This should be extracted dynamically if possible
  const timestamp = new Date().toISOString().replace('T', ' ').replace(/\.\d+/, '');
  
  // Extract module sections and their functions
  const modules = {};
  const moduleRegex = /\/\/ Inlined from: \.\/src\/([^\/]+)\/([^\/]+)\.d\.ts\s*\n([\s\S]*?)(?=\n\/\/ Inlined from:|$)/g;
  
  let match;
  while ((match = moduleRegex.exec(content)) !== null) {
    const [, mainCategory, subCategory, moduleContent] = match;
    
    // Extract function documentation from this module
    const functionDocs = [];
    const functionRegex = /\/\*\*\s*\n\s*\*\s*(.+?)\n\s*\*\s*@param\s+(\w+)\s+(.+?)\n(?:\s*\*\s*@return\s+(.+?)\n)?\s*\*\/\s*\n\s*(\w+)\s*\([^)]*\)\s*[:;]/gs;
    
    let funcMatch;
    while ((funcMatch = functionRegex.exec(moduleContent)) !== null) {
      const [, description, paramName, paramDesc, returnDesc, functionName] = funcMatch;
      functionDocs.push({
        name: functionName,
        description: description.trim(),
        params: [{ name: paramName, description: paramDesc.trim() }],
        returns: returnDesc ? returnDesc.trim() : 'void',
        subModule: subCategory
      });
    }
    
    // Group by main category (e.g., color, core, accessibility)
    if (functionDocs.length > 0) {
      if (!modules[mainCategory]) {
        modules[mainCategory] = [];
      }
      modules[mainCategory].push(...functionDocs);
    }
  }
  
  // Generate Vimdoc files per module
  console.log('📝 Generating Vimdoc files per module...');
  
  // Generate individual module files (one per main category)
  Object.entries(modules).forEach(([moduleName, functions]) => {
    const vimdocContent = createVimdocContent(moduleName, functions, p5Version, timestamp);
    fs.writeFileSync(path.join(outputDir, `p5-${moduleName}.txt`), vimdocContent);
  });
  
  // Generate main index file
  const indexContent = `*p5-modules*                             p5.js modules index

==============================================================================
Table of Contents                      *p5-modules-table-of-contents*

1. Available Modules                                     |p5-modules-available|

📚 p5.js Modules Documentation

📦 p5.js Version: ${p5Version}~
⏰ Last Updated: ${timestamp}~

==============================================================================
1. Available Modules                                     |p5-modules-available|

${Object.entries(modules).map(([moduleName, functions]) => {
  const moduleEmojis = {
    'accessibility': '♿',
    'color': '🎨',
    'core': '⚙️',
    'data': '📊',
    'dom': '🌐',
    'events': '🖱️',
    'image': '🖼️',
    'io': '📁',
    'math': '🔢',
    'typography': '📝',
    'utilities': '🛠️',
    'webgl': '🎮'
  };
  const emoji = moduleEmojis[moduleName] || '📚';
  return `- [${emoji} p5.${moduleName}](p5-${moduleName}.txt) - ${functions.length} functions`;
}).join('\n')}

## Total Functions
${Object.values(modules).reduce((total, functions) => total + functions.length, 0)} functions across ${Object.keys(modules).length} modules

==============================================================================
Generated by p5.nvim documentation generator <https://github.com/prjctimg/p5.nvim>

vim:tw=78:ts=8:ft=help:norl:
`;

  fs.writeFileSync(path.join(outputDir, 'p5-modules.txt'), indexContent);
  
  console.log(`✅ Generated ${Object.keys(modules).length} Vimdoc module files`);
  console.log(`📊 Total functions documented: ${Object.values(modules).reduce((total, functions) => total + functions.length, 0)}`);
}

try {
  extractDocumentation();
  console.log('🎉 Vimdoc documentation bundling complete! 📚🎉');
} catch (error) {
  console.error('❌ Error bundling documentation:', error.message);
  process.exit(1);
}