#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🚀 Starting p5 documentation generation...');

const outputDir = 'doc';

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

try {
  console.log('📖 Generating p5.js documentation...');
  
  // Create a simple documentation file
  const docContent = `# p5.js Documentation

Generated: ${new Date().toISOString()}

## Core Functions

This is a placeholder for p5.js documentation. In the actual workflow, this would contain:
- Complete API documentation
- Function references
- Examples
- Usage patterns

## Setup

\`\`\`javascript
function setup() {
  createCanvas(400, 400);
}
\`\`\`

## Draw

\`\`\`javascript
function draw() {
  background(220);
  // Your drawing code here
}
\`\`\`

---

*This documentation was automatically generated by the automata workflow.*
`;
  
  fs.writeFileSync(path.join(outputDir, 'p5.txt'), docContent);
  console.log('✅ Documentation generated!');
  console.log(`📁 Output written to: ${outputDir}/p5.txt`);
  
} catch (error) {
  console.error('❌ Error generating documentation:', error.message);
  process.exit(1);
}