/**
 * Template system for generating consistent Vim documentation
 */

export const VIMDOC_TEMPLATES = {
  // File header template
  header: `
{emoji} *{title}*{emoji}
{description}

==============================================================================
Tags {title} {description}
==============================================================================`,

  // Table of contents header
  tocHeader: 'CONTENTS                                                           *{moduleName}-contents*',

  // Section header template
  sectionHeader: `
{type}                                                   *{moduleName}-{type}*`,

  // Symbol template
  symbol: `
{tag} {emojiPrefix}
{signature}

{description}

{parameters}{returns}{examples}{source}`,

  // Parameter template
  parameter: '                {param}{description}',

  // Parameters wrapper
  parameters: `
Parameters: ~
{paramList}
~`,

  // Return value template
  returnValue: '                {return}',

  // Returns wrapper
  returns: `
Returns: ~
{returnList}
~`,

  // Example template
  example: `>
{exampleContent}`,

  // Examples wrapper
  examples: `
Example: >
{exampleList}
<`,

  // Source reference template
  source: `
Source: ~
                {sourcePath}
~`,

  // Deprecation warning template
  deprecation: `
⚠️  DEPRECATED: {deprecationMessage}`,

  // File footer template
  footer: `
==============================================================================
Generated by p5.js Documentation Automation
See: https://github.com/prjctimg/automata
Last updated: {date}
{emoji} End of {moduleName} documentation {emoji}
==============================================================================`
};

/**
 * Template for tags file header
 */
export const TAGS_TEMPLATE = `!_TAG_FILE_SORTED\t1\t/unknown field/
!_TAG_FILE_ENCODING\tutf-8\t/unknown field/
!_TAG_FILE_FORMAT\t2\t/extended format; --format=1 will not compatible with vi/

`;

/**
 * Format a template with provided variables
 * @param {string} template - Template string
 * @param {Object} variables - Variables to substitute
 * @returns {string} Formatted template
 */
export function formatTemplate(template, variables) {
  let result = template;
  
  for (const [key, value] of Object.entries(variables)) {
    const placeholder = `{${key}}`;
    const regex = new RegExp(placeholder.replace(/[{}]/g, '\\$&'), 'g');
    result = result.replace(regex, value || '');
  }
  
  return result;
}

/**
 * Format line with proper indentation for Vim
 * @param {string} content - Content to format
 * @param {number} indent - Number of spaces to indent
 * @returns {string} Formatted line
 */
export function formatLine(content, indent = 0) {
  return ' '.repeat(indent) + content;
}

/**
 * Wrap content at specific column width
 * @param {string} content - Content to wrap
 * @param {number} width - Maximum line width
 * @param {number} indent - Indentation for wrapped lines
 * @returns {string} Wrapped content
 */
export function wrapContent(content, width = 80, indent = 0) {
  if (content.length <= width) {
    return content;
  }
  
  const indentStr = ' '.repeat(indent);
  const words = content.split(' ');
  const lines = [];
  let currentLine = '';
  
  words.forEach(word => {
    if ((currentLine + word).length <= width) {
      currentLine += (currentLine ? ' ' : '') + word;
    } else {
      if (currentLine) {
        lines.push(currentLine);
        currentLine = word;
      } else {
        // Word is longer than width, break it
        lines.push(word.substring(0, width));
        currentLine = word.substring(width);
      }
    }
  });
  
  if (currentLine) {
    lines.push(currentLine);
  }
  
  return lines.join('\n' + indentStr);
}

/**
 * Create vim-compatible link
 * @param {string} text - Link text
 * @param {string} tag - Tag to link to
 * @returns {string} Vim link
 */
export function createVimLink(text, tag) {
  return `|${tag}|`;
}

/**
 * Format symbol name for documentation
 * @param {string} name - Symbol name
 * @param {string} type - Symbol type
 * @returns {string} Formatted name
 */
export function formatSymbolName(name, type) {
  if (type === 'function' || type === 'method') {
    return `${name}()`;
  }
  return name;
}