import fs from 'fs/promises';
import path from 'path';
import { ZigDocParser } from './zogDocParser.js';
import { getModuleEmoji, generateEmojiPrefix, formatParameterWithEmoji, formatReturnWithEmoji } from './emojiMapper.js';

/**
 * Generates Zig documentation files from parsed symbols
 */
export class ZigdocGenerator {
  constructor(config) {
    this.config = config;
    this.tags = new Map();
    this.generatedFiles = new Map();
  }

  /**
   * Generate all Zig documentation files
   * @param {Map} symbolsByModule - Symbols grouped by module
   * @param {string} outputDir - Output directory
   * @returns {Promise<Map>} Generated file paths
   */
  async generateAllFiles(symbolsByModule, outputDir) {
    console.log('🦎 Generating Zig documentation files...');
    
    // Ensure output directory exists
    await fs.mkdir(outputDir, { recursive: true });
    
    // Generate each module file
    for (const [moduleName, symbols] of symbolsByModule) {
      if (symbols.length === 0) continue;
      
      const filename = this.config.modules[moduleName]?.file || `zig-${moduleName}.zig`;
      const filepath = path.join(outputDir, filename);
      
      const content = this.generateZigFile(moduleName, symbols);
      await fs.writeFile(filepath, content, 'utf8');
      
      this.generatedFiles.set(moduleName, filepath);
      console.log(`✅ Generated ${filename} with ${symbols.length} symbols`);
    }
    
    // Generate index file
    await this.generateIndexFile(outputDir, symbolsByModule);
    
    console.log(`🦎 Generated ${this.generatedFiles.size} Zig documentation files`);
    return this.generatedFiles;
  }

  /**
   * Generate content for a single Zig module file
   * @param {string} moduleName - Module name
   * @param {Array} symbols - Array of symbols
   * @returns {string} File content
   */
  generateZigFile(moduleName, symbols) {
    const moduleConfig = this.config.modules[moduleName];
    const moduleEmoji = getModuleEmoji(moduleName);
    
    const content = [
      this.generateHeader(moduleName, moduleConfig, moduleEmoji),
      this.generateTableOfContents(symbols),
      this.generateSymbolSections(symbols),
      this.generateFooter(moduleName)
    ].join('\n\n');
    
    return content;
  }

  /**
   * Generate file header with Zig syntax
   * @param {string} moduleName - Module name
   * @param {Object} moduleConfig - Module configuration
   * @param {string} emoji - Module emoji
   * @returns {string} Header content
   */
  generateHeader(moduleName, moduleConfig, emoji) {
    const title = `std.${moduleName.charAt(0).toUpperCase() + moduleName.slice(1)}`;
    const description = moduleConfig?.description || `${moduleName} module functions and types`;
    
    return `/// ${emoji} ${title}
/// ${description}
/// 
/// Generated by p5.js Documentation Automation
/// ${new Date().toISOString().split('T')[0]}
/// 

pub const std = @import("std");

`;
  }

  /**
   * Generate table of contents for Zig documentation
   * @param {Array} symbols - Array of symbols
   * @returns {string} Table of contents
   */
  generateTableOfContents(symbols) {
    const sections = this.groupSymbolsByType(symbols);
    let toc = '/// Contents:\n';
    
    for (const [type, typeSymbols] of Object.entries(sections)) {
      if (typeSymbols.length === 0) continue;
      
      toc += `///   ${this.capitalizeFirst(type)}:\n`;
      typeSymbols.forEach(symbol => {
        const visibility = symbol.public ? '' : '(private)';
        toc += `///     ${symbol.name}${visibility}\n`;
      });
      toc += '\n';
    }
    
    return toc;
  }

  /**
   * Generate sections for all symbols
   * @param {Array} symbols - Array of symbols
   * @returns {string} Symbol sections content
   */
  generateSymbolSections(symbols) {
    const sections = this.groupSymbolsByType(symbols);
    let content = '';
    
    for (const [type, typeSymbols] of Object.entries(sections)) {
      if (typeSymbols.length === 0) continue;
      
      content += this.generateSectionHeader(type);
      
      typeSymbols.forEach(symbol => {
        content += this.generateSymbolDocumentation(symbol);
      });
      
      content += '\n';
    }
    
    return content;
  }

  /**
   * Generate section header
   * @param {string} type - Symbol type
   * @returns {string} Section header
   */
  generateSectionHeader(type) {
    return `/// 
/// ======================================================================
/// ${this.capitalizeFirst(type).toUpperCase()}
/// ======================================================================
/// 
`;
  }

  /**
   * Generate documentation for a single symbol
   * @param {Object} symbol - Symbol object
   * @returns {string} Symbol documentation
   */
  generateSymbolDocumentation(symbol) {
    const emojiPrefix = generateEmojiPrefix(symbol);
    let documentation = `/// ${emojiPrefix}\n`;
    
    // Declaration
    documentation += this.generateZigDeclaration(symbol);
    
    // Description
    if (symbol.description) {
      documentation += `/// \n/// ${symbol.description}\n`;
    }
    
    // Parameters
    if (symbol.parameters && symbol.parameters.length > 0) {
      documentation += this.generateParameters(symbol.parameters);
    }
    
    // Return value
    if (symbol.returns && symbol.returns.type !== 'void') {
      documentation += this.generateZigReturnType(symbol.returns);
    }
    
    // Examples
    if (symbol.examples && symbol.examples.length > 0) {
      documentation += this.generateZigExamples(symbol.examples);
    }
    
    return documentation + '\n';
  }

  /**
   * Generate Zig function/const/struct declaration
   * @param {Object} symbol - Symbol object
   * @returns {string} Zig declaration
   */
  generateZigDeclaration(symbol) {
    switch (symbol.type) {
      case 'function':
        return this.generateZigFunction(symbol);
      case 'constant':
        return this.generateZigConstant(symbol);
      case 'class':
        return this.generateZigStruct(symbol);
      case 'variable':
        return this.generateZigVariable(symbol);
      default:
        return `/// Unknown symbol type: ${symbol.type}\n`;
    }
  }

  /**
   * Generate Zig function declaration
   * @param {Object} symbol - Function symbol
   * @returns {string} Zig function declaration
   */
  generateZigFunction(symbol) {
    const params = symbol.parameters.map(param => {
      const type = this.normalizeZigType(param.type);
      const name = param.name;
      return `${name}: ${type}`;
    }).join(', ');
    
    const returnType = symbol.returns ? this.normalizeZigType(symbol.returns.type) : 'void';
    
    return `/// pub fn ${symbol.name}(${params}) ${returnType}`;
  }

  /**
   * Generate Zig constant declaration
   * @param {Object} symbol - Constant symbol
   * @returns {string} Zig constant declaration
   */
  generateZigConstant(symbol) {
    const type = this.normalizeZigType('unknown'); // Would need actual type detection
    return `/// pub const ${symbol.name}: ${type} = undefined; // TODO: Set actual value`;
  }

  /**
   * Generate Zig struct declaration
   * @param {Object} symbol - Struct symbol
   * @returns {string} Zig struct declaration
   */
  generateZigStruct(symbol) {
    return `/// pub const ${symbol.name} = struct {\n///     // TODO: Add fields\n/// }`;
  }

  /**
   * Generate Zig variable declaration
   * @param {Object} symbol - Variable symbol
   * @returns {string} Zig variable declaration
   */
  generateZigVariable(symbol) {
    const type = this.normalizeZigType('unknown'); // Would need actual type detection
    return `/// pub var ${symbol.name}: ${type} = undefined; // TODO: Initialize`;
  }

  /**
   * Generate parameter documentation
   * @param {Array} parameters - Array of parameters
   * @returns {string} Parameter documentation
   */
  generateParameters(parameters) {
    let docs = '/// \n/// Parameters:\n';
    
    parameters.forEach(param => {
      const formattedParam = formatParameterWithEmoji(param);
      docs += `///   ${formattedParam}: ${param.description || 'No description'}\n`;
    });
    
    return docs;
  }

  /**
   * Generate return type documentation
   * @param {Object} returns - Return type object
   * @returns {string} Return type documentation
   */
  generateZigReturnType(returns) {
    const formattedReturn = formatReturnWithEmoji(returns);
    return `/// \n/// Returns: ${formattedReturn.type}: ${formattedReturn.description}\n`;
  }

  /**
   * Generate Zig code examples
   * @param {Array} examples - Array of example strings
   * @returns {string} Example documentation
   */
  generateZigExamples(examples) {
    let docs = '/// \n/// Examples:\n';
    
    examples.forEach((example, index) => {
      docs += `/// Example ${index + 1}:\n`;
      const zigExample = this.convertToZigSyntax(example);
      docs += `/// ```zig\n/// ${zigExample}\n/// ```\n`;
    });
    
    return docs;
  }

  /**
   * Convert JavaScript example to Zig syntax
   * @param {string} jsExample - JavaScript example code
   * @returns {string} Zig equivalent code
   */
  convertToZigSyntax(jsExample) {
    // Basic JavaScript to Zig conversion
    return jsExample
      .replace(/function\s+(\w+)/g, 'pub fn $1')
      .replace(/const\s+(\w+)/g, 'const $1')
      .replace(/let\s+(\w+)/g, 'var $1')
      .replace(/===/g, '==')
      .replace(/!==/g, '!=')
      .replace(/console\.log/g, 'std.debug.print');
  }

  /**
   * Normalize type to Zig equivalent
   * @param {string} type - Original type
   * @returns {string} Zig type
   */
  normalizeZigType(type) {
    const typeMap = {
      'Number': 'f64',
      'String': '[]const u8',
      'Boolean': 'bool',
      'Array': '[]anytype',
      'Object': 'std.json.ValueMap',
      'void': 'void'
    };
    
    return typeMap[type] || type;
  }

  /**
   * Group symbols by type for organization
   * @param {Array} symbols - Array of symbols
   * @returns {Object} Symbols grouped by type
   */
  groupSymbolsByType(symbols) {
    const groups = {
      functions: [],
      constants: [],
      classes: [],
      variables: []
    };
    
    symbols.forEach(symbol => {
      const type = symbol.type === 'function' ? 'functions' :
                 symbol.type === 'constant' ? 'constants' :
                 symbol.type === 'class' ? 'classes' :
                 'variables';
      
      if (groups[type]) {
        groups[type].push(symbol);
      }
    });
    
    return groups;
  }

  /**
   * Generate index file
   * @param {string} outputDir - Output directory
   * @param {Map} symbolsByModule - Symbols grouped by module
   */
  async generateIndexFile(outputDir, symbolsByModule) {
    const indexPath = path.join(outputDir, 'index.zig');
    
    let content = '/// Generated Zig Documentation Index\n/// \n';
    content += '/// Generated by p5.js Documentation Automation\n/// \n';
    content += `/// ${new Date().toISOString()}\n/// \n`;
    content += '/// \n';
    
    content += 'pub const modules = struct {\n';
    symbolsByModule.forEach((symbols, moduleName) => {
      const normalized = moduleName.replace(/[-\s]/g, '_');
      content += `    /// ${normalized}: @import("std-${normalized}.zig"),\n`;
    });
    content += '};\n';
    
    await fs.writeFile(indexPath, content, 'utf8');
    console.log('✅ Generated index.zig');
  }

  /**
   * Generate file footer
   * @param {string} moduleName - Module name
   * @returns {string} Footer content
   */
  generateFooter(moduleName) {
    const emoji = getModuleEmoji(moduleName);
    return `/// 
/// ======================================================================
/// End of ${moduleName} documentation
/// ======================================================================
/// ${emoji}
`;
  }

  /**
   * Capitalize first letter
   * @param {string} str - String to capitalize
   * @returns {string} Capitalized string
   */
  capitalizeFirst(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  /**
   * Get all generated files
   * @returns {Map} Generated files map
   */
  getGeneratedFiles() {
    return this.generatedFiles;
  }

  /**
   * Get all generated tags
   * @returns {Map} Generated tags map
   */
  getGeneratedTags() {
    return this.tags;
  }
}